### ISSUE TITLE
Investigate projects with actuals before project start date

### ISSUE THREAD

**Issue by hcastro1989** [hcastro1989/Cognitive-Delivery#22]

**Comment by areyes13** [comment]
<img width="631" alt="screen shot 2017-01-13 at 5 39 58 pm" src="https://cloud.githubusercontent.com/assets/7623984/21948167/5ef7eff4-d9b7-11e6-8aa3-903ceaa3fbeb.png">

Double check in the source files to see if the issue is coming from the source (as in the screenshot above) or if it is something wrong with the import/cleanup of the cube.
